version: '2'
services:
  sa-apollo-proxy: 
    container_name: sa-apollo-proxy
    image: diefrodriguezcha/sa_apollo_proxy:latest
    depends_on:
      - sa-apollo-api
    ports:
      - 80:80
    labels:
        io.rancher.container.pull_image: always
        io.rancher.scheduler.affinity:host_label: hostproxy=true
  sa-apollo-api:
    container_name: sa-apollo-api
    image: diefrodriguezcha/sa-apollov2-api:latest
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      CENTERS_URL: 'sa-centers-ms'
      CENTERS_ENTRY: 'courses-ms/resources/courses'
      CENTERS_PORT: '3001'
      NEWSLETTERS_URL: 'sa-news-ms'
      NEWSLETTERS_PORT: '3002'
      USERS_URL: 'sa-user-ms'
      USERS_ENTRY: 'api/auth'
      USERS_PORT: '3003'
    links:
      - sa-centers-ms
      - sa-user-ms
      - sa-news-ms
    expose:
      - '5000'
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label_ne: noapi=true
      io.rancher.container.pull_image: always
  sa-user-db:
    container_name: sa-user-db
    image: mongo
    ports:
      - 27017:27017
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: hostproxy=true
  sa-news-db:
    container_name: sa-news-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: railsapp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: appuser
    ports:
      - 3306:3306
    labels:
      io.rancher.scheduler.affinity:host_label: hostdb=true
      io.rancher.container.pull_image: always
  courses-db:
    container_name: courses-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: courses-db
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: sa
    ports:
      - 3307:3306
    labels:
      io.rancher.scheduler.affinity:host_label: hostdb=true
      io.rancher.container.pull_image: always
  sa-user-ms:
    container_name: sa-user-ms
    image: diefrodriguezcha/sa_user_ms
    environment:
      DATABASE: '27017'
      DOCKER_DEPLOY: 'true'
      LDAP: '35.196.42.82'
      LDAP_PORT: '389'
      PORT: '3003'
      SECRET: arquisoft
    depends_on:
      - sa-user-db
    links:
      - sa-user-db
    expose:
      - '3003'
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.pull_image: always
  sa-news-ms:
    container_name: sa-news-ms
    image: menoguera/newsletter-api
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    environment:
      DB_HOST: sa-news-db
      DB_NAME: railsapp
      DB_PASSWORD: password
      DB_USER: root
      PORT: '3002'
    depends_on:
      - sa-news-db
    links:
      - sa-news-db
    expose:
      - '3002'
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: hostdb=true
      io.rancher.container.pull_image: always
  sa-centers-ms:
    container_name: sa-centers-ms
    image: dulfrey/sa_centers_ms
    depends_on:
      - courses-db
    links:
      - courses-db
    expose:
      - '3001'
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: hostdb=true
      io.rancher.container.pull_image: always
  sa-apollo-wa:
    image: menoguera/sa-front-web 
    command: 'npm start'
    ports:
      - '4200:4200' 
    expose:
      - '4200' 
    labels:
      io.rancher.scheduler.affinity:host_label_ne: nofront=true
      io.rancher.container.pull_image: always
  sa-apolloapi-lb:
    image: rancher/lb-service-haproxy:v0.9.6
    ports:
      - 5000:5000/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: hostproxy=true
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  sa-apollowa-lb:
    image: rancher/lb-service-haproxy:v0.9.6
    ports:
      - 4201:4201/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: hostproxy=true
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true' 
  sa-phpldapadmin-ms:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_HTTPS: 'false'
      PHPLDAPADMIN_LDAP_HOSTS: sa-apollo-ldap
    links:
      - sa-apollo-ldap:sa-apollo-ldap
    ports:
      - 8085:80/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: hostproxy=true
  sa-apollo-ldap:
    image: osixia/openldap:1.1.8
    hostname: apollo.org
    environment:
      COMPOSE_HTTP_TIMEOUT: '200'
      LDAP_ADMIN_PASSWORD: admin
      LDAP_BACKEND: hdb
      LDAP_BASE_DN: ''
      LDAP_CONFIG_PASSWORD: config
      LDAP_DOMAIN: apollo.unal.edu.co
      LDAP_LOG_LEVEL: '256'
      LDAP_ORGANISATION: Apollo UN
      LDAP_READONLY_USER: 'false'
      LDAP_REMOVE_CONFIG_AFTER_SETUP: 'true'
      LDAP_REPLICATION: 'false'
      LDAP_SSL_HELPER_PREFIX: ldap
      LDAP_TLS: 'true'
      LDAP_TLS_CA_CRT_FILENAME: ca.crt
      LDAP_TLS_CIPHER_SUITE: SECURE256:-VERS-SSL3.0
      LDAP_TLS_CRT_FILENAME: ldap.crt
      LDAP_TLS_ENFORCE: 'false'
      LDAP_TLS_KEY_FILENAME: ldap.key
      LDAP_TLS_PROTOCOL_MIN: '3.1'
      LDAP_TLS_VERIFY_CLIENT: demand
    stdin_open: true
    volumes:
      - /container/service/slapd/assets/certs/
      - /etc/ldap/slapd.d
      - /var/lib/ldap
    tty: true
    ports:
      - 389:389/tcp
      - 636:636/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: hostproxy=true
  sa-bot-db:
    image: mongo
    ports:
      - 27027:27027/tcp
    command:
      - mongod
      - --port
      - '27027'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: hostproxy=true
  sa-bot-ms:
    image: diefrodriguezcha/sa_bot_ms:latest
    environment:
      DATABASE: '27027'
      DOCKER_DEPLOY: 'true'
      PORT: '3000'
    links:
      - sa-bot-db:sa-bot-db
    ports:
      - 3000:80/tcp  
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.pull_image: always