version: '2'
services:
  sa-news-db:
    scale: 2
    start_on_create: true
  courses-db:
    scale: 2
    start_on_create: true
  sa-user-ms:
    scale: 3
    start_on_create: true
  sa-news-ms:
    scale: 2
    start_on_create: true
  sa-centers-ms:
    scale: 2
    start_on_create: true
  sa-user-db:
    scale: 1
    start_on_create: true
  sa-apollo-proxy:
    scale: 1
    start_on_create: true
  sa-phpldapadmin-ms:
    scale: 1
    start_on_create: true
  sa-apollo-ldap:
    scale: 1
    start_on_create: true
  sa-bot-db:
    scale: 1
    start_on_create: true
  sa-bot-ms:
    scale: 3
    start_on_create: true
  sa-apollo-api:
    scale: 3
    start_on_create: true
  sa-front-wa:
    scale: 3
    start_on_create: true
  sa-apolloapi-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        path: ''
        priority: 1
        protocol: http
        service: sa-apollo-api
        source_port: 5000
        target_port: 5000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  sa-apollowa-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: sa-front-wa
        source_port: 4201
        target_port: 4200
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000